
package com.example.examcswclient.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.examcsw.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.examcsw.example.com/", className = "com.example.examcswclient.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.examcsw.example.com/", className = "com.example.examcswclient.service.SaveResponse")
    @Action(input = "http://service.examcsw.example.com/ProductService/saveRequest", output = "http://service.examcsw.example.com/ProductService/saveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.examcswclient.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://service.examcsw.example.com/", className = "com.example.examcswclient.service.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://service.examcsw.example.com/", className = "com.example.examcswclient.service.GetListResponse")
    @Action(input = "http://service.examcsw.example.com/ProductService/getListRequest", output = "http://service.examcsw.example.com/ProductService/getListResponse")
    public List<Product> getList();

}
